# Generated by Django 2.1.4 on 2019-01-17 10:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0002_auto_20190117_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Package Title')),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('GM-CM', 'Gm-cm'), ('Pound-Inch', 'Pound-Inch')], max_length=30)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 17, 10, 4, 16, 519159, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 1, 17, 10, 4, 16, 519178, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Product Title')),
                ('image', models.ImageField(blank=True, upload_to='products/images/')),
                ('sku', models.CharField(blank=True, max_length=200, verbose_name='SKU')),
                ('upc', models.CharField(blank=True, max_length=200, verbose_name='UPC')),
                ('ean', models.CharField(max_length=200, unique=True, verbose_name='EAN')),
                ('model_number', models.CharField(blank=True, max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('detail', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 17, 10, 4, 16, 518459, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 1, 17, 10, 4, 16, 518476, tzinfo=utc))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.Category', verbose_name='Select Category')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.Color', verbose_name='Select Color')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.Size', verbose_name='Select Size')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.Status', verbose_name='Select Status')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 17, 10, 4, 16, 519618, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 1, 17, 10, 4, 16, 519636, tzinfo=utc))),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.Color', verbose_name='Select Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.Size', verbose_name='Select Size')),
            ],
        ),
        migrations.AddField(
            model_name='packagemeasurement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
