# Generated by Django 2.1.4 on 2019-01-04 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190104_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemeasurement',
            name='depth',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='packagemeasurement',
            name='length',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='packagemeasurement',
            name='weight',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='packagemeasurement',
            name='width',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 16, 40, 29, 509530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
