# Generated by Django 2.1.4 on 2019-01-09 08:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190107_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemeasurement',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 8, 47, 35, 185828, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='packagemeasurement',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 8, 47, 35, 185846, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 8, 47, 35, 185197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagemeasurement',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Package Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Select Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Color', verbose_name='Select Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 8, 47, 35, 185167, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(max_length=200, unique=True, verbose_name='EAN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Size', verbose_name='Select Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=200, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Product Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.CharField(blank=True, max_length=200, verbose_name='UPC'),
        ),
    ]
