# Generated by Django 2.1.4 on 2019-01-18 11:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20190118_1133'),
        ('products', '0006_auto_20190117_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Product Title')),
                ('image', models.ImageField(blank=True, upload_to='products/amazon/images/')),
                ('seller_sku', models.CharField(blank=True, max_length=200, verbose_name='Seller SKU')),
                ('asin', models.CharField(blank=True, max_length=200, verbose_name='ASIN')),
                ('units_per_box', models.IntegerField()),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 618287, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 618307, tzinfo=utc))),
                ('amazonmarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.AmazonMarket', verbose_name='Select Amazon Marketplace')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.Box', verbose_name='Select Box')),
            ],
        ),
        migrations.AlterField(
            model_name='packagemeasurement',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 617296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagemeasurement',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 617317, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 616556, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 616574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 617739, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 617755, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='packagemeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.PackageMeasurement', verbose_name='Select Package'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Select Product'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.Status', verbose_name='Select Status'),
        ),
    ]
