# Generated by Django 2.1.4 on 2019-02-01 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20190201_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbundle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productbundle',
            name='size',
        ),
        migrations.AddField(
            model_name='productbundle',
            name='bundle_product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bundle_product', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 13, 37, 18, 178699, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 13, 37, 18, 178715, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagemeasurement',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 13, 37, 18, 177721, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagemeasurement',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 13, 37, 18, 177739, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 13, 37, 18, 177046, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 13, 37, 18, 177067, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 13, 37, 18, 178135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 13, 37, 18, 178151, tzinfo=utc)),
        ),
    ]
