# Generated by Django 2.1.4 on 2019-02-05 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20190205_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='asin',
            field=models.CharField(max_length=50, verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='box',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='settings.Box', verbose_name='Select Box'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 28, 0, 68535, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='packagemeasurement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='products.PackageMeasurement', verbose_name='Select Package'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Select Product'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='units_per_box',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 28, 0, 68556, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagemeasurement',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 28, 0, 67552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagemeasurement',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 28, 0, 67573, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 28, 0, 66843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 28, 0, 66861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 28, 0, 67989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 28, 0, 68006, tzinfo=utc)),
        ),
    ]
