# Generated by Django 2.1.4 on 2019-02-20 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0110_auto_20190219_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Length (cm)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Width (cm)')),
                ('depth', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Depth (cm)')),
                ('cbm', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='CBM')),
                ('units_per_box', models.IntegerField()),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 2, 20, 9, 53, 41, 227902, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 2, 20, 9, 53, 41, 227922, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='box',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='products.Box', verbose_name='Select Box'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 9, 53, 41, 228489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 9, 53, 41, 228507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagemeasurement',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 9, 53, 41, 226640, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packagemeasurement',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 9, 53, 41, 226686, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 9, 53, 41, 225842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 9, 53, 41, 225871, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 9, 53, 41, 227171, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 9, 53, 41, 227189, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='box',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_product', to='products.Product'),
        ),
    ]
