# Generated by Django 2.1.4 on 2019-01-17 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20190117_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=10)),
                ('domain', models.CharField(max_length=50)),
                ('amazon_id', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 17, 15, 39, 37, 194585, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 1, 17, 15, 39, 37, 194602, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='currency',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 15, 39, 37, 194234, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 15, 39, 37, 194252, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='status',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 15, 39, 37, 193805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='status',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 15, 39, 37, 193834, tzinfo=utc)),
        ),
    ]
