# Generated by Django 2.1.4 on 2019-01-18 11:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20190117_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonmarket',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 615710, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='amazonmarket',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 615727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='box',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 615362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='box',
            name='depth',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Depth (cm)'),
        ),
        migrations.AlterField(
            model_name='box',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Length (cm)'),
        ),
        migrations.AlterField(
            model_name='box',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 615378, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='box',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Width (cm)'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 615029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 615048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='status',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 614587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='status',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 33, 51, 614615, tzinfo=utc)),
        ),
    ]
