# Generated by Django 2.1.4 on 2019-01-23 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_auto_20190123_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonMwsauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(choices=[('US', 'US'), ('Europe', 'Europe'), ('Japan', 'Japan')], default='US', max_length=30, verbose_name='Select Identifier')),
                ('seller_id', models.CharField(max_length=50, verbose_name='Seller ID')),
                ('auth_token', models.CharField(max_length=100, verbose_name='Auth Token')),
                ('access_key', models.CharField(max_length=100, verbose_name='Access Key')),
                ('secret_key', models.CharField(max_length=100, verbose_name='Secret Key')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 23, 9, 28, 6, 780736, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 1, 23, 9, 28, 6, 780752, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='amazonmarket',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 9, 28, 6, 780355, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='amazonmarket',
            name='identifier',
            field=models.CharField(choices=[('US', 'US'), ('Europe', 'Europe'), ('Japan', 'Japan')], default='US', max_length=30, verbose_name='Select Identifier'),
        ),
        migrations.AlterField(
            model_name='amazonmarket',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 9, 28, 6, 780375, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='box',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 9, 28, 6, 779985, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='box',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 9, 28, 6, 780001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 9, 28, 6, 779665, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 9, 28, 6, 779682, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='status',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 9, 28, 6, 779205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='status',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 9, 28, 6, 779323, tzinfo=utc)),
        ),
    ]
