# Generated by Django 2.1.4 on 2019-01-21 09:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0007_auto_20190121_0914'),
        ('settings', '0009_auto_20190121_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('packing_type', models.CharField(choices=[('Individual', 'Individual'), ('Case-packed', 'Case-packed')], max_length=50)),
                ('type', models.CharField(choices=[('Air', 'Air'), ('Sea', 'Sea')], max_length=20)),
                ('kg_cbm_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Kg/CBM Price')),
                ('invoice_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prepaid_vat', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prepaid VAT')),
                ('actual_vat', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Actual VAT')),
                ('vat_claimed', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='VAT Claimed')),
                ('pickup_date', models.DateTimeField(blank=True, verbose_name='Select Pickup date')),
                ('eta', models.DateTimeField(blank=True, verbose_name='Select ETA')),
                ('etd', models.DateTimeField(blank=True, verbose_name='Select ETD')),
                ('tracking_id', models.CharField(blank=True, max_length=100, verbose_name='Tracking ID')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 21, 9, 14, 42, 959997, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 1, 21, 9, 14, 42, 960015, tzinfo=utc))),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrier', to='suppliers.Supplier', verbose_name='Select Carrier')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.Currency', verbose_name='Select Currency')),
                ('invoice_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_agent', to='suppliers.Supplier', verbose_name='Select Invoice Agent')),
                ('invoice_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency_invoice', to='settings.Currency', verbose_name='Select Invoice Currency')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers.Order', verbose_name='Select Order')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.Status', verbose_name='Select Status')),
                ('vat_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency_vat', to='settings.Currency', verbose_name='Select VAT Currency')),
            ],
        ),
    ]
