# Generated by Django 2.1.4 on 2019-01-21 09:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_auto_20190121_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 9, 48, 0, 730140, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 9, 48, 0, 730159, tzinfo=utc)),
        ),
    ]
