# Generated by Django 2.1.4 on 2019-01-21 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_auto_20190121_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='actual_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Actual VAT'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 10, 13, 39, 92745, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='eta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Select ETA'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='etd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Select ETD'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Select Pickup date'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tracking ID'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 10, 13, 39, 92762, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vat_claimed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='VAT Claimed'),
        ),
    ]
