# Generated by Django 2.1.4 on 2019-01-21 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20190121_1209'),
        ('shipping', '0008_auto_20190121_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_send', models.IntegerField()),
                ('quantity_received', models.IntegerField()),
                ('missing_units', models.IntegerField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 21, 12, 9, 20, 110627, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 1, 21, 12, 9, 20, 110644, tzinfo=utc))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product', verbose_name='Select Product')),
            ],
        ),
        migrations.AlterField(
            model_name='shipment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 12, 9, 20, 109894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 12, 9, 20, 109910, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='shipmentproduct',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.Shipment', verbose_name='Select Shipment'),
        ),
    ]
