# Generated by Django 2.1.4 on 2019-01-21 12:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20190121_1227'),
        ('shipping', '0010_auto_20190121_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentproduct',
            name='amazonproduct',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='products.AmazonProduct', verbose_name='Select Amazon Market Product'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 12, 27, 22, 9666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 12, 27, 22, 9683, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproduct',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 12, 27, 22, 10340, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproduct',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 12, 27, 22, 10356, tzinfo=utc)),
        ),
    ]
