# Generated by Django 2.1.4 on 2019-01-23 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import shipping.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0025_auto_20190123_1337'),
        ('shipping', '0016_auto_20190123_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_url', models.FileField(upload_to=shipping.models.generate_shipmentfilename)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 23, 13, 37, 27, 156659, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 1, 23, 13, 37, 27, 156678, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentFullfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=30)),
                ('country_code', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 23, 13, 37, 27, 153835, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 1, 23, 13, 37, 27, 153852, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='amazon_labelprep',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='amazon_shipment_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='amazonmarket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='settings.AmazonMarket', verbose_name='Select MarketPlace'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 13, 37, 27, 154456, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 13, 37, 27, 154471, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproduct',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 13, 37, 27, 156083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproduct',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 13, 37, 27, 156114, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='shipmentfiles',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.Shipment', verbose_name='Select Shipment'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='amazon_fullfillment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shipping.ShipmentFullfillment'),
        ),
    ]
