# Generated by Django 2.1.4 on 2019-02-22 12:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0114_auto_20190222_1221'),
        ('shipping', '0107_auto_20190221_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentproductorderdelivery',
            name='orderdeliveryproduct',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='suppliers.OrderDeliveryProduct', verbose_name='Select Order Delivery Product'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 12, 21, 22, 67623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 12, 21, 22, 67643, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentfiles',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 12, 21, 22, 69992, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentfiles',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 12, 21, 22, 70009, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentfullfillment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 12, 21, 22, 66968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentfullfillment',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 12, 21, 22, 66989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproduct',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 12, 21, 22, 69070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproduct',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 12, 21, 22, 69088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproductorderdelivery',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 12, 21, 22, 69548, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproductorderdelivery',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 12, 21, 22, 69564, tzinfo=utc)),
        ),
    ]
