# Generated by Django 2.1.4 on 2019-02-25 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0108_auto_20190222_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_prepaid_vat',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 7, 11, 9, 916582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 7, 11, 9, 916600, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentfiles',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 7, 11, 9, 918571, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentfiles',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 7, 11, 9, 918587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentfullfillment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 7, 11, 9, 915864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentfullfillment',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 7, 11, 9, 915887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproduct',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 7, 11, 9, 917656, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproduct',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 7, 11, 9, 917674, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproductorderdelivery',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 7, 11, 9, 918152, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproductorderdelivery',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 7, 11, 9, 918168, tzinfo=utc)),
        ),
    ]
