# Generated by Django 2.1.4 on 2019-02-25 16:13

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0109_auto_20190225_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 13, 45, 671066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='invoice_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 13, 45, 671082, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentfiles',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 13, 45, 673731, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentfiles',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 13, 45, 673753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentfullfillment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 13, 45, 670387, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentfullfillment',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 13, 45, 670412, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproduct',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 13, 45, 672764, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproduct',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 13, 45, 672784, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproductorderdelivery',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 13, 45, 673274, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentproductorderdelivery',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 16, 13, 45, 673291, tzinfo=utc)),
        ),
    ]
