# Generated by Django 2.1.4 on 2019-01-09 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20190109_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200)),
                ('prepay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('days', models.IntegerField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 9, 14, 31, 40, 119598, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 1, 9, 14, 31, 40, 119615, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 9, 14, 31, 40, 119929, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 1, 9, 14, 31, 40, 119947, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 14, 31, 40, 118289, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='category',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 14, 31, 40, 118307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 14, 31, 40, 118833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 14, 31, 40, 118851, tzinfo=utc)),
        ),
    ]
