# Generated by Django 2.1.4 on 2019-01-11 12:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import suppliers.models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0022_auto_20190111_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 446239, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 446258, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='AqlFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_url', models.FileField(upload_to=suppliers.models.generate_aqlfilename)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 446704, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 446727, tzinfo=utc))),
                ('aql', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.Aql', verbose_name='Select AQL')),
            ],
        ),
        migrations.AlterField(
            model_name='bank',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 442848, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bank',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 442864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 440279, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 440303, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 442312, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 442327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 443296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 443312, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 441975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 441992, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mold',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 444479, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mold',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 444505, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moldfile',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 445719, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moldfile',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 445746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moldproduct',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 445183, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moldproduct',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 445205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paymentterms',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 441413, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paymentterms',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 441429, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 443707, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 443723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='status',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 441709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='status',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 441726, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 440850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 12, 38, 53, 440869, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='aql',
            name='productprice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.ProductPrice', verbose_name='Select Product'),
        ),
    ]
